name: dala_ishchisi
description: "Dala ishchisi"
publish_to: 'none'
version: 2.0.0+1
build_type: prod # prod|stage

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  archive: ^4.0.5
  auto_route: ^10.0.1
  bloc: ^9.0.0
  cached_network_image: ^3.4.1
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  device_preview: ^1.2.0
  dio: ^5.8.0+1
  dio_cache_interceptor: ^3.5.1
  dio_cache_interceptor_hive_store: ^4.0.0
  easy_localization: ^3.0.7+1
  encrypt: ^5.0.3
  flutter_bloc: ^9.1.0
  flutter_easyloading: ^3.0.5
  flutter_svg: ^2.0.17
  fluttertoast: ^8.2.12
  freezed_annotation: ^2.4.4
  get_it: ^8.0.3
  geolocator: ^14.0.0
  google_fonts: ^6.2.1
  google_maps_flutter: ^2.12.1
  heroicons: ^0.11.0
  hive: ^2.2.3
  image_picker: ^1.1.2
  injectable: ^2.5.0
  internet_connection_checker_plus: ^2.7.1
  json_annotation: ^4.9.0
  map_launcher: ^3.5.0
  package_info_plus: ^8.3.0
  path_provider: ^2.1.5   # not support web
  pointer_interceptor: ^0.10.1+2
  pull_to_refresh: ^2.0.0
  safe_device: ^1.2.1      # not support web
  share_plus: ^11.0.0
  shimmer: ^3.0.0
  url_launcher: ^6.3.1
  widget_and_text_animator: ^1.1.5
  rename_app: ^1.6.3
  mbtiles: ^0.4.2
  latlong2: ^0.9.1
  sqlite3_flutter_libs: ^0.5.34
  flutter_map: ^8.1.1
  flutter_downloader: ^1.12.0
  permission_handler: ^12.0.0+1
  api_client_common:
    path: ./api_client/common
  api_client_crop:
    path: ./api_client/crop
  api_client_dictionaries:
    path: ./api_client/dictionaries
  api_client_identity:
    path: ./api_client/identity
  built_collection: ^5.1.1
  built_value: ^8.11.0

dev_dependencies:
  auto_route_generator: ^10.0.1
  build_runner: ^2.4.15
  flutter_launcher_icons: ^0.14.3
  flutter_lints: ^5.0.0
  freezed: ^2.5.8
  injectable_generator: ^2.7.0
  json_serializable: ^6.9.4
  prompt_generator: ^0.0.4
  res_generator: ^0.1.5


flutter_icons:
  android: true
  image_path: "assets/images/logo.png"
  adaptive_icon_background: "#FFFFFF"

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
    - assets/tr/
